### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by Svetomech** [ZeeRooo/MaterialFBook#11]
Please, update [MaterialFBook on F-Droid.org](https://f-droid.org/repository/browse/?fdfilter=MaterialFB&fdid=me.zeeroooo.materialfb) to the [latest apk available in your repository](https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.0.0.apk). It is much more convenient to install it from there than doing so by hand every time a new version is released.

**Comment by ZeeRooo** [comment]
Who uploaded my app yo fdroid?

**Comment by Svetomech** [comment]
It wasn't you?

**Comment by est31** [comment]
Hello, F-Droid packager here (I didn't upload the app in question, but I see it was outdated):

* [F-Droid](https://f-droid.org) is an Android app store exclusively for **open source** apps. See F-Droid's [Wikipedia page](https://en.wikipedia.org/wiki/F-Droid).
* You can browse the catalog of available apps on [Fossdroid](https://fossdroid.com/), or on the [official website](https://f-droid.org/repository/browse/).
* You don't upload your apk file to F-Droid, instead you maintain a build script that includes how to build the app and where its source code are. This is the [link to your build script](https://gitlab.com/fdroid/fdroiddata/blob/8a7a0b9b18c86fd75be3eff9a2ca61e13bbfc451/metadata/me.zeeroooo.materialfb.txt).
* While some apps maintain their build script in the F-Droid repo, this is not common among all apps. You still can if you want to!
* I wanted to update the app but saw that you didn't raise the version code for new releases. Due to how android works, and how F-Droid is built, this is not possible, and if you upload to the play store you will run into problems as well. In order to make an update possible, we need a bumped version code (usually its bumped with every release just as the version name).

**Comment by ZeeRooo** [comment]
@est31 Sorry but where is the problem? Can you explain it more? (why you couldnt update the app and why i cant upload it to Play Store)

**Comment by est31** [comment]
@ZeeRooo you need to raise this number with every release: https://github.com/ZeeRooo/MaterialFBook/blob/e153e4ce97da9bd14c6376a23d8934fd557dcb09/app/build.gradle#L15

**Comment by ZeeRooo** [comment]
@est31 Omg haha. Sorry for this, i havent idea xD
Later im going to upload new version with this and other issues fixed

**Comment by ZeeRooo** [comment]
@est31 Try now, i changed it in version v2.1.0

**Comment by krt16s** [comment]
Ref: https://gitlab.com/fdroid/fdroiddata/commit/ed7a2d59c0e801c481aa36d3359f660d1d7b8983

**Comment by ZeeRooo** [comment]
@krt16s  Nice, thank you!
