### ISSUE TITLE
Main Activity displays no posts on home

### ISSUE THREAD

**Issue by fabmazz** [ZeeRooo/MaterialFBook#13]
Loading the post feed, the website is loaded but then the whole area goes blank. Messages and notifications are displayed correctly

**Comment by ZeeRooo** [comment]
Yes, this is a new feature. Please disable "Hide news feed" in options and it works correctly.

**Comment by fabmazz** [comment]
Ah, well, now I went to settings, enabled and then disabled the hide news
feed option and now it works.
Maybe it was set to yes during the update.

Il 14 nov 2016 16:39, "Juan" <notifications@github.com> ha scritto:

**Comment by ZeeRooo** [comment]
Yes, this is a new feature, please disable "hide news feed" option in
settings.

El nov. 14, 2016 11:32, "Fabio Mazza" <notifications@github.com> escribió:

Loading the post feed, the website is loaded but then the whole area goes
blank. Messages and notifications are displayed correctly

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/13>, or mute the thread
