### ISSUE TITLE
MaterialFBook loading up like it's data saving/facebook lite

### ISSUE THREAD

**Issue by kevin0110w** [ZeeRooo/MaterialFBook#147]
Hello,

MaterialFBook (ver 3.6.8, can't install 3.7.5 strangely) loads up like it's in data saving/facebook lite avatars are out, badges etc ..

For what it's worth, face slim seems to be having this issue too but not slim social.

Thanks.
![20180409_122331](https://user-images.githubusercontent.com/37250646/38492977-e4a6974e-3bf0-11e8-860b-a53ca914867b.jpg)

**Comment by landry314** [comment]
This was fixed in the newest version as per issue #141.

You can download it here:
https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.7.5.apk

but messenger doesn't work so you might want to wait for a day to get the next version.

It will be posted here as usual:
https://github.com/ZeeRooo/MaterialFBook/tree/master/apks

**Comment by kevin0110w** [comment]
I didn't realise I had to uninstall very 3.6.8, before attempting to reinstall the newer release. All working now =)

**Comment by kevin0110w** [comment]
I didn't realise I had to uninstall very 3.6.8, before attempting to reinstall the newer release. All working now =)
