### ISSUE TITLE
Keep F-Droid version updated

### ISSUE THREAD

**Issue by Airon90** [ZeeRooo/MaterialFBook#20]
[MaterialFBook on F-Droid](https://f-droid.org/repository/browse?fdid=me.zeeroooo.materialfb) is not updated to the latest version. Could you fix this problem? Thank you very much

**Comment by ZeeRooo** [comment]
Same as #18 I cant do anything.

**Comment by landry314** [comment]
maybe you can ask either f-droid or the person uploading materialfbook to take control of the f-droid version.

**Comment by ZeeRooo** [comment]
Always the same question..

El dic. 23, 2016 19:29, "Landry Racoon" <notifications@github.com> escribió:

maybe you can ask either f-droid or the person uploading materialfbook to
take control of the f-droid version.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/20#issuecomment-269052400>,
or mute the thread
