### ISSUE TITLE
reverse from link, start from beginnig

### ISSUE THREAD

**Issue by dklueh79** [ZeeRooo/MaterialFBook#27]
if you click a link and go back, the last position in news or any other post isn't saves.  you always start from beginning of the posts.

**Comment by ZeeRooo** [comment]
This bug was fixed in **v2.5.0**

You can **download** it from here: https://raw.githubusercontent.com/ZeeRooo/MaterialFBook/master/apks/MaterialFBook_2.5.0.apk

Sorry for the late

**Comment by dklueh79** [comment]
Thanx! Could you please put the new version into the fdroid store?

**Comment by ZeeRooo** [comment]
Im not a member of F-Droid. They will release my app in a few days or
weeks, i dont know if the server have updated the SDK.
#18

**Comment by dklueh79** [comment]
It still happens. Opening a link in a browser, closing it via return oder going back, you'll sometimes will bei pushed back to the start of the posts

**Comment by ZeeRooo** [comment]
No in 2.5.0+

El feb. 8, 2017 1:49, "Daniel Klüh" <notifications@github.com> escribió:

It still happens. Opening a link in a browser, closing it via return oder
going back, you'll sometimes will bei pushed back to the start of the posts

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/27#issuecomment-278228593>,
or mute the thread
