### ISSUE TITLE
reseparate "notifications" and "messages notifications"

### ISSUE THREAD

**Issue by landry314** [ZeeRooo/MaterialFBook#47]
i want notifications for messages but not for silly facebook notifications. why did you combine these into one option? why are you taking away features?

**Comment by ZeeRooo** [comment]
Because i re-made the notification system and forget separate the
notification. In the next version i'll add the option to messages and
notifications

El feb. 14, 2017 15:35, "Landry Racoon" <notifications@github.com> escribió:

i want notifications for messages but not for silly facebook notifications.
why did you combine these into one option? why are you taking away features?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/47>, or mute the thread

**Comment by landry314** [comment]
thank you!

**Comment by ZeeRooo** [comment]
I separated "Messages" from "Notifications" in the **2.7.5**

You can **download** it from here: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_2.7.5.apk?raw=true
