### ISSUE TITLE
App is not displayed in share contextual menu

### ISSUE THREAD

**Issue by darksidecorrales** [ZeeRooo/MaterialFBook#63]
Hi! In some apps (for example QuickPic) when I tap share button, the app is not appears in the menu for directly share.
https://youtu.be/g7NsfUI_ypE

**Comment by ZeeRooo** [comment]
Yes, i know. Its very hard to implement because i dont know much about CSS.

**Comment by darksidecorrales** [comment]
Ohm...

**Comment by ZeeRooo** [comment]
I have been implemented **QuickShare** feature to share images and videos from gallery, but, for now, its only avaible for testers because im waiting to Facebook to aprove _"publish_permissions"_ on MFB.

If you want to use the feature right now, the only way is join in the testers section of MFB Facebook SDK with your fbid. See: http://i.imgur.com/oMfhWKf.png

And the latest version is: https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.3.0.apk
