### ISSUE TITLE
Change mandatory Facebook permissions request to optional

### ISSUE THREAD

**Issue by Bitim** [ZeeRooo/MaterialFBook#91]
I'm reopening this issue (https://github.com/ZeeRooo/MaterialFBook/issues/67), because @ZeeRooo didn't answer on the old issue.

**Comment by creativetrendsapps** [comment]
@Bitim these permissions aren't mandatory you can opt out of them when logging in. You just won't see your information within the navigation drawer. These permissions are also public permissions that are granted by default: https://developers.facebook.com/docs/facebook-login/android/permissions. The dev of MaterialFbook doesn't get to read or access your information. User information is anonymous. Also, this issue was answered in full detail. With a full explanation as to why these permissions are requested in #67 .

**Comment by ZeeRooo** [comment]
@Bitim Check the B-350. I deleted all Fb Sdk, so you can remove the app permissions from your account.

**Comment by Bitim** [comment]
@ZeeRooo thanks!
