### ISSUE TITLE
Constant "something went wrong"

### ISSUE THREAD

**Issue by gappleto97** [ZeeRooo/MaterialFBook#99]
I cannot do anything in the app anymore. I suspect Facebook changed some things.

**Comment by ZeeRooo** [comment]
Are you using the last version avaible? **3.4.5**

**Comment by gappleto97** [comment]
I have 3.4.1, the latest on FDroid.

It looks like the problem is with "share article". Once I do that, if I can't go back to a Facebook page, then nothing works.

**Comment by ZeeRooo** [comment]
Update to the latest version avaible in my repo... I switched to the old
id, but i dont know if fdroid update my app.

El jul. 29, 2017 13:18, "Gabe Appleton" <notifications@github.com> escribió:

I have 3.4.1, the latest on FDroid.

It looks like the problem is with "share article". Once I do that, if I
can't go back to a Facebook page, then nothing works.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ZeeRooo/MaterialFBook/issues/99#issuecomment-318841428>,
or mute the thread
